- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: valkey
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: https://valkey-io.github.io/valkey-helm
      chart: valkey
      targetRevision: v0.3.0
      helm:
        valueFiles:
          - https://raw.githubusercontent.com/UthayakumarRakav/cuegrowth-devops-assessment/main/infra/helm/valkey/valkey-values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: cuegrowth
    syncPolicy:
      automated: { prune: true, selfHeal: true }
---
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: nats
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: https://nats-io.github.io/k8s/helm/charts/
      chart: nats
      targetRevision: 0.14.0
      helm:
        valueFiles:
          - https://raw.githubusercontent.com/UthayakumarRakav/cuegrowth-devops-assessment/main/infra/helm/nats/nats-values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: cuegrowth
    syncPolicy:
      automated: { prune: true, selfHeal: true }
---
# Custom apps
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: api
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: https://github.com/UthayakumarRakav/cuegrowth-devops-assessment.git
      path: infra/helm/api
      targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: cuegrowth
    syncPolicy:
      automated: { prune: true, selfHeal: true }
---
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: worker
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: https://github.com/UthayakumarRakav/cuegrowth-devops-assessment.git
      path: infra/helm/worker
      targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: cuegrowth
    syncPolicy:
      automated: { prune: true, selfHeal: true }
