apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cuegrowth-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UthayakumarRakav/cuegrowth-devops-assessment.git
    path: infra
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
