apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cuegrowth-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/UthayakumarRakav/cuegrowth-devops-assessment.git'
    targetRevision: HEAD
    path: infra
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cuegrowth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
