apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats
  namespace: cuegrowth
  labels:
    team: cuegrowth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  namespaceSelector:
    matchNames:
      - cuegrowth
  endpoints:
    - port: metrics
      interval: 30s
