apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://valkey-io.github.io/valkey-helm
    chart: valkey
    targetRevision: v0.3.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/UthayakumarRakav/cuegrowth-devops-assessment/main/infra/helm/valkey/valkey-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cuegrowth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
